# Schema for the configuration files of the Domain 301 Redirect module.

domain_301_redirect.settings:
  type: config_object
  label: 'Domain 301 redirect settings'
  mapping:
    enabled:
      type: integer
      label: 'Enable to start 301 redirects to the domain'
    domain:
      type: string
      label: 'Domain'
    check_period:
      type: integer
      label: 'Selects the period between domain'
    domain_check_retries:
      type: integer
      label: 'Number of times to check domain availability'
    domain_check_reenable:
      type: boolean
      label: 'Re-enable domain redirection'
    disabled_by_check:
      type: boolean
      label: 'Disable domain redirection'
    last_checked:
      type: integer
      label: 'Redirect is disabled by cron'
    loop_max_redirects:
      type: integer
      label: 'Loop maximum redirects'
    applicability:
      type: integer
      label: 'Redirect on specific pages'
    pages:
      type: string
      label: 'Specify pages'
    redirect_last_checked:
      type: integer
      label: 'The unix timestamp of the last time a scheduled domain redirect check was performed.'
